// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ApolloProvider = require("reason-apollo/src/ApolloProvider.bs.js");
var Client$ReactTemplate = require("./Client.bs.js");
var SortedRepos$ReactTemplate = require("./SortedRepos.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, ApolloProvider.make(Client$ReactTemplate.instance("YOUR TOKEN"), /* array */[
              React.createElement("h1", undefined, "Goals 1"),
              ReasonReact.element(/* None */0, /* None */0, SortedRepos$ReactTemplate.make(/* array */[]))
            ])), "main");

/*  Not a pure module */
